version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: postgress
    restart: always
    environment:
      POSTGRES_USER: ${postgress_login}
      POSTGRES_PASSWORD: ${postgress_password}
      POSTGRES_DB: ${POSTGRES_DB}
    # ports:
    #   - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql:Z
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:Z
    networks:
      - app_network
  my_bot:
    build: ./bot           # Путь до папки с Dockerfile бота
    container_name: bot
    #restart: always
    volumes:
      - ./bot:/app:Z
    environment:
      - TOKEN=${BOT_TOKEN}
      - TOKEN_AI=${TOKEN_AI}
      - TG_ADMIN_ID=${admin_id}
      - POSTGRES_USER=${postgress_login}
      - POSTGRES_PASSWORD=${postgress_password}
      - POSTGRES_DB=${POSTGRES_DB}
    # ports:
    #   - "8080:80"
    networks:
      - app_network

  server:
    build: ./site          
    container_name: site
    stop_signal: SIGKILL
    restart: always
    ports:
      - "${PORT}:443"
    environment:
      - POSTGRES_USER=${postgress_login}
      - POSTGRES_PASSWORD=${postgress_password}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app_network
    depends_on:
      - db
  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    environment:
      - NGROK_AUTHTOKEN=${NGROK_TOKEN}
    command:
      - "http"
      - "https://server:443"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
    
volumes:
  db_data: